/* Written by scripts/gen-notices.py from the licence files; do not edit.
   The notices of what is linked into the executable, for the F1 help
   window (owner, 2026-09-29: the executable is offered on its own). */
#include "rubraview/notices.h"

static const char *const LINES[] = {
    "==== THIRD_PARTY_NOTICES.md ====",
    "# Third-Party Notices",
    "",
    "Rubraview ships as a single executable that statically links the",
    "libraries below. Their licence texts travel with the binary; the full",
    "provenance record for each is in `docs/resources/sources-and-licenses.md`.",
    "",
    "## proven_c_lib",
    "",
    "- Vendored snapshot at `vendor/proven/`",
    "- Licence: MIT \xE2""\x80""\x94"" see `vendor/proven/LICENSE`",
    "- Used for: memory arenas, UTF-8 string slices, dynamic collections, and",
    "  the job scheduler behind the pre-cache worker.",
    "- Additional notices from that project: `vendor/proven/THIRD_PARTY_NOTICES.md`",
    "",
    "## miniz 3.1.2",
    "",
    "- Vendored snapshot at `vendor/miniz/`",
    "- Copyright 2013-2014 RAD Game Tools and Valve Software; copyright",
    "  2010-2014 Rich Geldreich and Tenacious Software LLC",
    "- Licence: MIT \xE2""\x80""\x94"" see `vendor/miniz/LICENSE`",
    "- Used for: DEFLATE decompression of CBZ (ZIP) entries only. The ZIP",
    "  container itself is parsed by rubraview's own reader.",
    "",
    "## LZMA SDK 24.08",
    "",
    "- Vendored snapshot at `vendor/lzma/` (decode subset; see",
    "  `vendor/lzma/VENDORED.md` for exactly which files and why)",
    "- Written and placed in the **public domain** by Igor Pavlov. Some of it",
    "  is based on public-domain code by other authors: PPMd var.H (2001) by",
    "  Dmitry Shkarin.",
    "- Licence text: `vendor/lzma/LICENSE.txt`",
    "- Used for: reading 7z (CB7) comic archives, including the solid blocks",
    "  \xC2""\xA7""3.8.2 needs a persistent decoder for. No encoder, no file I/O and no",
    "  encryption support is included.",
    "- Public domain imposes no condition; this notice is credit, not",
    "  compliance.",
    "",
    "## UnRAR 7.3.1 (converted to C)",
    "",
    "- Converted to C at `vendor/unrar-c/` (see `vendor/unrar-c/VENDORED.md`):",
    "  the decompression of RAR 1.5 to 7.0 archives and the decryption of",
    "  RAR 3.x to 5.0 ones, for reading CBR comics.",
    "- Copyright Alexander L. Roshal. Licence text: `vendor/unrar-c/LICENSE.txt`.",
    "- UnRAR source code may be used in any software to handle RAR archives",
    "  without limitations free of charge, but cannot be used to develop RAR",
    "  (WinRAR) compatible archiver and to re-create RAR compression algorithm,",
    "  which is proprietary. Distribution of modified UnRAR source code in",
    "  separate form or as a part of other software is permitted, provided that",
    "  full text of this paragraph, starting from \"UnRAR source code\" words, is",
    "  included in license, or in documentation if license is not available,",
    "  and in source code comments of resulting package.",
    "- Rubraview only reads RAR archives; it cannot make one.",
    "",
    "## libjpeg-turbo 3.0.4",
    "",
    "- Vendored snapshot at `vendor/libjpeg-turbo/` (the libjpeg API library",
    "  only; see `vendor/libjpeg-turbo/VENDORED.md`)",
    "- This software is based in part on the work of the Independent JPEG",
    "  Group. Copyright (C) 1991-2020, Thomas G. Lane, Guido Vollbeding;",
    "  libjpeg-turbo modifications copyright (C) 2009-2024, D. R. Commander",
    "  and others.",
    "- Licences: the IJG License (`vendor/libjpeg-turbo/README.ijg`) and the",
    "  Modified 3-clause BSD License (`vendor/libjpeg-turbo/LICENSE.md`).",
    "  Both are attribution-only.",
    "- Used for: rotating and flipping JPEGs by rearranging their DCT",
    "  coefficients, and stripping metadata, without decoding any pixel. No",
    "  encoder, no file I/O, no SIMD and no arithmetic coding is included.",
    "",
    "Nothing else in the tree is third-party code. The Windows platform",
    "libraries (Direct2D, DirectWrite, the Windows Imaging Component, WASAPI)",
    "are operating-system components, not bundled dependencies.",
    "",
    "## FFmpeg (headers only, not shipped)",
    "",
    "rubraview can play media through FFmpeg when its DLLs are present beside",
    "the executable. To compile those calls, the public headers of FFmpeg",
    "8.1.2 are kept in `vendor/ffmpeg/include/`; they are licensed",
    "LGPL-2.1-or-later (`vendor/ffmpeg/COPYING.LGPLv2.1`).",
    "",
    "No FFmpeg code is compiled into rubraview and none is distributed with",
    "it: the functions are looked up at run time from DLLs the user provides.",
    "Windows Media Foundation remains the default decoder (D-8).",
    "",
    "",
    "==== LICENSE ====",
    "MIT License",
    "",
    "Copyright (c) 2026 rubidus",
    "",
    "Permission is hereby granted, free of charge, to any person obtaining a copy",
    "of this software and associated documentation files (the \"Software\"), to deal",
    "in the Software without restriction, including without limitation the rights",
    "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
    "copies of the Software, and to permit persons to whom the Software is",
    "furnished to do so, subject to the following conditions:",
    "",
    "The above copyright notice and this permission notice shall be included in all",
    "copies or substantial portions of the Software.",
    "",
    "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR",
    "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,",
    "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE",
    "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER",
    "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,",
    "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE",
    "SOFTWARE.",
    "",
    "==== vendor/proven/LICENSE ====",
    "MIT License",
    "",
    "Copyright (c) 2026 rubidus-api",
    "",
    "Permission is hereby granted, free of charge, to any person obtaining a copy",
    "of this software and associated documentation files (the \"Software\"), to deal",
    "in the Software without restriction, including without limitation the rights",
    "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
    "copies of the Software, and to permit persons to whom the Software is",
    "furnished to do so, subject to the following conditions:",
    "",
    "The above copyright notice and this permission notice shall be included in all",
    "copies or substantial portions of the Software.",
    "",
    "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR",
    "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,",
    "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE",
    "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER",
    "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,",
    "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE",
    "SOFTWARE.",
    "",
    "==== vendor/proven/THIRD_PARTY_NOTICES.md ====",
    "# Third-Party Notices",
    "",
    "## Float parse rewrite",
    "",
    "The decimal-to-binary64 parsing work under `src/proven/float_decimal.c` and",
    "`src/proven/float_parse.c` is a clean-room implementation for this repository.",
    "",
    "- No implementation code was copied or ported from `glibc`, `musl`,",
    "  `MSVCRT`, `BSD libc`, `fast_float`, `double-conversion`, or similar parser",
    "  libraries.",
    "- The design direction follows public algorithm descriptions only:",
    "  - Clinger-style exact fast paths for small decimal values",
    "  - Eisel-Lemire-family fast-path structure and cached-power concepts",
    "  - exact midpoint comparison for the fallback path",
    "- Any cached `5^q` constants currently present in the source are direct exact",
    "  integer values generated by `scripts/generate_float_decimal_tables.py`, not",
    "  imported tables.",
    "",
    "The current codebase still uses a bigint exact fallback as the main",
    "correctness path for difficult inputs. Additional fast paths must preserve the",
    "same clean-room rule: use original code and project-local constants only.",
    "",
    "==== vendor/miniz/LICENSE ====",
    "Copyright 2013-2014 RAD Game Tools and Valve Software",
    "Copyright 2010-2014 Rich Geldreich and Tenacious Software LLC",
    "",
    "All Rights Reserved.",
    "",
    "Permission is hereby granted, free of charge, to any person obtaining a copy",
    "of this software and associated documentation files (the \"Software\"), to deal",
    "in the Software without restriction, including without limitation the rights",
    "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
    "copies of the Software, and to permit persons to whom the Software is",
    "furnished to do so, subject to the following conditions:",
    "",
    "The above copyright notice and this permission notice shall be included in",
    "all copies or substantial portions of the Software.",
    "",
    "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR",
    "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,",
    "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE",
    "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER",
    "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,",
    "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN",
    "THE SOFTWARE.",
    "",
    "==== vendor/lzma/LICENSE.txt ====",
    "LZMA SDK 24.08",
    "--------------",
    "",
    "LZMA SDK provides the documentation, samples, header files,",
    "libraries, and tools you need to develop applications that",
    "use 7z / LZMA / LZMA2 / XZ compression.",
    "",
    "LZMA is an improved version of famous LZ77 compression algorithm.",
    "It was improved in way of maximum increasing of compression ratio,",
    "keeping high decompression speed and low memory requirements for",
    "decompressing.",
    "",
    "LZMA2 is a LZMA based compression method. LZMA2 provides better",
    "multithreading support for compression than LZMA and some other improvements.",
    "",
    "7z is a file format for data compression and file archiving.",
    "7z is a main file format for 7-Zip compression program (www.7-zip.org).",
    "7z format supports different compression methods: LZMA, LZMA2 and others.",
    "7z also supports AES-256 based encryption.",
    "",
    "XZ is a file format for data compression that uses LZMA2 compression.",
    "XZ format provides additional features: SHA/CRC check, filters for",
    "improved compression ratio, splitting to blocks and streams,",
    "",
    "",
    "",
    "LICENSE",
    "-------",
    "",
    "LZMA SDK is written and placed in the public domain by Igor Pavlov.",
    "",
    "Some code in LZMA SDK is based on public domain code from another developers:",
    "  1) PPMd var.H (2001): Dmitry Shkarin",
    "  2) SHA-256: Wei Dai (Crypto++ library)",
    "",
    "Anyone is free to copy, modify, publish, use, compile, sell, or distribute the",
    "original LZMA SDK code, either in source code form or as a compiled binary, for",
    "any purpose, commercial or non-commercial, and by any means.",
    "",
    "LZMA SDK code is compatible with open source licenses, for example, you can",
    "include it to GNU GPL or GNU LGPL code.",
    "",
    "",
    "LZMA SDK Contents",
    "-----------------",
    "",
    "  Source code:",
    "",
    "    - C / C++ / C# / Java   - LZMA compression and decompression",
    "    - C / C++               - LZMA2 compression and decompression",
    "    - C / C++               - XZ compression and decompression",
    "    - C                     - 7z decompression",
    "    -     C++               - 7z compression and decompression",
    "    - C                     - small SFXs for installers (7z decompression)",
    "    -     C++               - SFXs and SFXs for installers (7z decompression)",
    "",
    "  Precomiled binaries:",
    "",
    "    - console programs for lzma / 7z / xz compression and decompression",
    "    - SFX modules for installers.",
    "",
    "",
    "UNIX/Linux version",
    "------------------",
    "There are several otpions to compile 7-Zip with different compilers: gcc and clang.",
    "Also 7-Zip code contains two versions for some critical parts of code: in C and in Assembeler.",
    "So if you compile the version with Assembeler code, you will get faster 7-Zip binary.",
    "",
    "7-Zip's assembler code uses the following syntax for different platforms:",
    "",
    "1) x86 and x86-64 (AMD64): MASM syntax.",
    "   There are 2 programs that supports MASM syntax in Linux.",
    "'    'Asmc Macro Assembler and JWasm. But JWasm now doesn't support some",
    "      cpu instructions used in 7-Zip.",
    "   So you must install Asmc Macro Assembler in Linux, if you want to compile fastest version",
    "   of 7-Zip  x86 and x86-64:",
    "     https://github.com/nidud/asmc",
    "",
    "2) arm64: GNU assembler for ARM64 with preprocessor.",
    "   That systax of that arm64 assembler code in 7-Zip is supported by GCC and CLANG for ARM64.",
    "",
    "There are different binaries that can be compiled from 7-Zip source.",
    "There are 2 main files in folder for compiling:",
    "  makefile        - that can be used for compiling Windows version of 7-Zip with nmake command",
    "  makefile.gcc    - that can be used for compiling Linux/macOS versions of 7-Zip with make command",
    "",
    "At first you must change the current folder to folder that contains `makefile.gcc`:",
    "",
    "  cd CPP/7zip/Bundles/Alone7z",
    "",
    "Then you can compile `makefile.gcc` with the command:",
    "",
    "  make -j -f makefile.gcc",
    "",
    "Also there are additional \"*.mak\" files in folder \"CPP/7zip/\" that can be used to compile",
    "7-Zip binaries with optimized code and optimzing options.",
    "",
    "To compile with GCC without assembler:",
    "  cd CPP/7zip/Bundles/Alone7z",
    "  make -j -f ../../cmpl_gcc.mak",
    "",
    "To compile with CLANG without assembler:",
    "  make -j -f ../../cmpl_clang.mak",
    "",
    "To compile 7-Zip for x86-64 with asmc assembler:",
    "  make -j -f ../../cmpl_gcc_x64.mak",
    "",
    "To compile 7-Zip for arm64 with assembler:",
    "  make -j -f ../../cmpl_gcc_arm64.mak",
    "",
    "To compile 7-Zip for arm64 for macOS:",
    "  make -j -f ../../cmpl_mac_arm64.mak",
    "",
    "Also you can change some compiler options in the mak files:",
    "  cmpl_gcc.mak",
    "  var_gcc.mak",
    "  warn_gcc.mak",
    "",
    "",
    "",
    "Also you can use p7zip (port of 7-Zip for POSIX systems like Unix or Linux):",
    "",
    "  http://p7zip.sourceforge.net/",
    "",
    "",
    "Files",
    "-----",
    "",
    "DOC/7zC.txt          - 7z ANSI-C Decoder description",
    "DOC/7zFormat.txt     - 7z Format description",
    "DOC/installer.txt    - information about 7-Zip for installers",
    "DOC/lzma.txt         - LZMA compression description",
    "DOC/lzma-sdk.txt     - LZMA SDK description (this file)",
    "DOC/lzma-history.txt - history of LZMA SDK",
    "DOC/lzma-specification.txt - Specification of LZMA",
    "DOC/Methods.txt      - Compression method IDs for .7z",
    "",
    "bin/installer/   - example script to create installer that uses SFX module,",
    "",
    "bin/7zdec.exe    - simplified 7z archive decoder (x86 32-bit version)",
    "bin/7zr.exe      - 7-Zip console program (reduced version) (x86 32-bit version)",
    "bin/x64/7zr.exe  - 7-Zip console program (reduced version) (x64 version)",
    "bin/x64/7zdec.exe  - simplified 7z archive decoder (x64 version)",
    "bin/arm64/7zr.exe  - 7-Zip console program (reduced version) (arm64 version)",
    "bin/arm64/7zdec.exe  - simplified 7z archive decoder (arm64 version)",
    "bin/lzma.exe     - file->file LZMA encoder/decoder for Windows",
    "bin/7zS2.sfx     - small SFX module for installers (GUI version)",
    "bin/7zS2con.sfx  - small SFX module for installers (Console version)",
    "bin/7zSD.sfx     - SFX module for installers.",
    "",
    "",
    "7zDec.exe",
    "---------",
    "7zDec.exe is simplified 7z archive decoder.",
    "It supports only LZMA, LZMA2, and PPMd methods.",
    "7zDec decodes whole solid block from 7z archive to RAM.",
    "The RAM consumption can be high.",
    "",
    "",
    "",
    "",
    "Source code structure",
    "---------------------",
    "",
    "",
    "Asm/ - asm files (optimized code for CRC calculation and Intel-AES encryption)",
    "",
    "C/  - C files (compression / decompression and other)",
    "  Util/",
    "    7z       - 7z decoder program (decoding 7z files)",
    "    Lzma     - LZMA program (file->file LZMA encoder/decoder).",
    "    LzmaLib  - LZMA library (.DLL for Windows)",
    "    SfxSetup - small SFX module for installers",
    "",
    "CPP/ -- CPP files",
    "",
    "  Common  - common files for C++ projects",
    "  Windows - common files for Windows related code",
    "",
    "  7zip    - files related to 7-Zip",
    "",
    "    Archive - files related to archiving",
    "",
    "      Common   - common files for archive handling",
    "      7z       - 7z C++ Encoder/Decoder",
    "",
    "    Bundles  - Modules that are bundles of other modules (files)",
    "",
    "      Alone7z       - 7zr.exe: Standalone 7-Zip console program (reduced version)",
    "      Format7zExtractR  - 7zxr.dll: Reduced version of 7z DLL: extracting from 7z/LZMA/BCJ/BCJ2.",
    "      Format7zR         - 7zr.dll:  Reduced version of 7z DLL: extracting/compressing to 7z/LZMA/BCJ/BCJ2",
    "      LzmaCon       - lzma.exe: LZMA compression/decompression",
    "      LzmaSpec      - example code for LZMA Specification",
    "      SFXCon        - 7zCon.sfx: Console 7z SFX module",
    "      SFXSetup      - 7zS.sfx: 7z SFX module for installers",
    "      SFXWin        - 7z.sfx: GUI 7z SFX module",
    "",
    "    Common   - common files for 7-Zip",
    "",
    "    Compress - files for compression/decompression",
    "",
    "    Crypto   - files for encryption / decompression",
    "",
    "    UI       - User Interface files",
    "",
    "      Client7z - Test application for 7za.dll, 7zr.dll, 7zxr.dll",
    "      Common   - Common UI files",
    "      Console  - Code for console program (7z.exe)",
    "      Explorer    - Some code from 7-Zip Shell extension",
    "      FileManager - Some GUI code from 7-Zip File Manager",
    "      GUI         - Some GUI code from 7-Zip",
    "",
    "",
    "CS/ - C# files",
    "  7zip",
    "    Common   - some common files for 7-Zip",
    "    Compress - files related to compression/decompression",
    "      LZ     - files related to LZ (Lempel-Ziv) compression algorithm",
    "      LZMA         - LZMA compression/decompression",
    "      LzmaAlone    - file->file LZMA compression/decompression",
    "      RangeCoder   - Range Coder (special code of compression/decompression)",
    "",
    "Java/  - Java files",
    "  SevenZip",
    "    Compression    - files related to compression/decompression",
    "      LZ           - files related to LZ (Lempel-Ziv) compression algorithm",
    "      LZMA         - LZMA compression/decompression",
    "      RangeCoder   - Range Coder (special code of compression/decompression)",
    "",
    "",
    "Note:",
    "  Asm / C / C++ source code of LZMA SDK is part of 7-Zip's source code.",
    "  7-Zip's source code can be downloaded from 7-Zip's SourceForge page:",
    "",
    "  http://sourceforge.net/projects/sevenzip/",
    "",
    "",
    "",
    "LZMA features",
    "-------------",
    "  - Variable dictionary size (up to 1 GB)",
    "  - Estimated compressing speed: about 2 MB/s on 2 GHz CPU",
    "  - Estimated decompressing speed:",
    "      - 20-30 MB/s on modern 2 GHz cpu",
    "      - 1-2 MB/s on 200 MHz simple RISC cpu: (ARM, MIPS, PowerPC)",
    "  - Small memory requirements for decompressing (16 KB + DictionarySize)",
    "  - Small code size for decompressing: 5-8 KB",
    "",
    "LZMA decoder uses only integer operations and can be",
    "implemented in any modern 32-bit CPU (or on 16-bit CPU with some conditions).",
    "",
    "Some critical operations that affect the speed of LZMA decompression:",
    "  1) 32*16 bit integer multiply",
    "  2) Mispredicted branches (penalty mostly depends from pipeline length)",
    "  3) 32-bit shift and arithmetic operations",
    "",
    "The speed of LZMA decompressing mostly depends from CPU speed.",
    "Memory speed has no big meaning. But if your CPU has small data cache,",
    "overall weight of memory speed will slightly increase.",
    "",
    "",
    "How To Use",
    "----------",
    "",
    "Using LZMA encoder/decoder executable",
    "--------------------------------------",
    "",
    "Usage:  LZMA <e|d> inputFile outputFile [<switches>...]",
    "",
    "  e: encode file",
    "",
    "  d: decode file",
    "",
    "  b: Benchmark. There are two tests: compressing and decompressing",
    "     with LZMA method. Benchmark shows rating in MIPS (million",
    "     instructions per second). Rating value is calculated from",
    "     measured speed and it is normalized with Intel's Core 2 results.",
    "     Also Benchmark checks possible hardware errors (RAM",
    "     errors in most cases). Benchmark uses these settings:",
    "     (-a1, -d21, -fb32, -mfbt4). You can change only -d parameter.",
    "     Also you can change the number of iterations. Example for 30 iterations:",
    "       LZMA b 30",
    "     Default number of iterations is 10.",
    "",
    "<Switches>",
    "",
    "",
    "  -a{N}:  set compression mode 0 = fast, 1 = normal",
    "          default: 1 (normal)",
    "",
    "  d{N}:   Sets Dictionary size - [0, 30], default: 23 (8MB)",
    "          The maximum value for dictionary size is 1 GB = 2^30 bytes.",
    "          Dictionary size is calculated as DictionarySize = 2^N bytes.",
    "          For decompressing file compressed by LZMA method with dictionary",
    "          size D = 2^N you need about D bytes of memory (RAM).",
    "",
    "  -fb{N}: set number of fast bytes - [5, 273], default: 128",
    "          Usually big number gives a little bit better compression ratio",
    "          and slower compression process.",
    "",
    "  -lc{N}: set number of literal context bits - [0, 8], default: 3",
    "          Sometimes lc=4 gives gain for big files.",
    "",
    "  -lp{N}: set number of literal pos bits - [0, 4], default: 0",
    "          lp switch is intended for periodical data when period is",
    "          equal 2^N. For example, for 32-bit (4 bytes)",
    "          periodical data you can use lp=2. Often it's better to set lc0,",
    "          if you change lp switch.",
    "",
    "  -pb{N}: set number of pos bits - [0, 4], default: 2",
    "          pb switch is intended for periodical data",
    "          when period is equal 2^N.",
    "",
    "  -mf{MF_ID}: set Match Finder. Default: bt4.",
    "              Algorithms from hc* group doesn't provide good compression",
    "              ratio, but they often works pretty fast in combination with",
    "              fast mode (-a0).",
    "",
    "              Memory requirements depend from dictionary size",
    "              (parameter \"d\" in table below).",
    "",
    "               MF_ID     Memory                   Description",
    "",
    "                bt2    d *  9.5 + 4MB  Binary Tree with 2 bytes hashing.",
    "                bt3    d * 11.5 + 4MB  Binary Tree with 3 bytes hashing.",
    "                bt4    d * 11.5 + 4MB  Binary Tree with 4 bytes hashing.",
    "                hc4    d *  7.5 + 4MB  Hash Chain with 4 bytes hashing.",
    "",
    "  -eos:   write End Of Stream marker. By default LZMA doesn't write",
    "          eos marker, since LZMA decoder knows uncompressed size",
    "          stored in .lzma file header.",
    "",
    "  -si:    Read data from stdin (it will write End Of Stream marker).",
    "  -so:    Write data to stdout",
    "",
    "",
    "Examples:",
    "",
    "1) LZMA e file.bin file.lzma -d16 -lc0",
    "",
    "compresses file.bin to file.lzma with 64 KB dictionary (2^16=64K)",
    "and 0 literal context bits. -lc0 allows to reduce memory requirements",
    "for decompression.",
    "",
    "",
    "2) LZMA e file.bin file.lzma -lc0 -lp2",
    "",
    "compresses file.bin to file.lzma with settings suitable",
    "for 32-bit periodical data (for example, ARM or MIPS code).",
    "",
    "3) LZMA d file.lzma file.bin",
    "",
    "decompresses file.lzma to file.bin.",
    "",
    "",
    "Compression ratio hints",
    "-----------------------",
    "",
    "Recommendations",
    "---------------",
    "",
    "To increase the compression ratio for LZMA compressing it's desirable",
    "to have aligned data (if it's possible) and also it's desirable to locate",
    "data in such order, where code is grouped in one place and data is",
    "grouped in other place (it's better than such mixing: code, data, code,",
    "data, ...).",
    "",
    "",
    "Filters",
    "-------",
    "You can increase the compression ratio for some data types, using",
    "special filters before compressing. For example, it's possible to",
    "increase the compression ratio on 5-10% for code for those CPU ISAs:",
    "x86, IA-64, ARM, ARM-Thumb, PowerPC, SPARC.",
    "",
    "You can find C source code of such filters in C/Bra*.* files",
    "",
    "You can check the compression ratio gain of these filters with such",
    "7-Zip commands (example for ARM code):",
    "No filter:",
    "  7z a a1.7z a.bin -m0=lzma",
    "",
    "With filter for little-endian ARM code:",
    "  7z a a2.7z a.bin -m0=arm -m1=lzma",
    "",
    "It works in such manner:",
    "Compressing    = Filter_encoding + LZMA_encoding",
    "Decompressing  = LZMA_decoding + Filter_decoding",
    "",
    "Compressing and decompressing speed of such filters is very high,",
    "so it will not increase decompressing time too much.",
    "Moreover, it reduces decompression time for LZMA_decoding,",
    "since compression ratio with filtering is higher.",
    "",
    "These filters convert CALL (calling procedure) instructions",
    "from relative offsets to absolute addresses, so such data becomes more",
    "compressible.",
    "",
    "For some ISAs (for example, for MIPS) it's impossible to get gain from such filter.",
    "",
    "",
    "",
    "---",
    "",
    "http://www.7-zip.org",
    "http://www.7-zip.org/sdk.html",
    "http://www.7-zip.org/support.html",
    "",
    "==== vendor/unrar-c/LICENSE.txt ====",
    " ******    *****   ******   UnRAR - free utility for RAR archives",
    " **   **  **   **  **   **  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    " ******   *******  ******    License for use and distribution of",
    " **   **  **   **  **   **   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    " **   **  **   **  **   **         FREE portable version",
    "                                   ~~~~~~~~~~~~~~~~~~~~~",
    "",
    "      The source code of UnRAR utility is freeware. This means:",
    "",
    "   1. All copyrights to RAR and the utility UnRAR are exclusively",
    "      owned by the author - Alexander Roshal.",
    "",
    "   2. UnRAR source code may be used in any software to handle",
    "      RAR archives without limitations free of charge, but cannot be",
    "      used to develop RAR (WinRAR) compatible archiver and to",
    "      re-create RAR compression algorithm, which is proprietary.",
    "      Distribution of modified UnRAR source code in separate form",
    "      or as a part of other software is permitted, provided that",
    "      full text of this paragraph, starting from \"UnRAR source code\"",
    "      words, is included in license, or in documentation if license",
    "      is not available, and in source code comments of resulting package.",
    "",
    "   3. The UnRAR utility may be freely distributed. It is allowed",
    "      to distribute UnRAR inside of other software packages.",
    "",
    "   4. THE RAR ARCHIVER AND THE UnRAR UTILITY ARE DISTRIBUTED \"AS IS\".",
    "      NO WARRANTY OF ANY KIND IS EXPRESSED OR IMPLIED.  YOU USE AT",
    "      YOUR OWN RISK. THE AUTHOR WILL NOT BE LIABLE FOR DATA LOSS,",
    "      DAMAGES, LOSS OF PROFITS OR ANY OTHER KIND OF LOSS WHILE USING",
    "      OR MISUSING THIS SOFTWARE.",
    "",
    "   5. Installing and using the UnRAR utility signifies acceptance of",
    "      these terms and conditions of the license.",
    "",
    "   6. If you don't agree with terms of the license you must remove",
    "      UnRAR files from your storage devices and cease to use the",
    "      utility.",
    "",
    "      Thank you for your interest in RAR and UnRAR.",
    "",
    "",
    "                                            Alexander L. Roshal",
    "",
    "==== vendor/libjpeg-turbo/LICENSE.md ====",
    "libjpeg-turbo Licenses",
    "======================",
    "",
    "libjpeg-turbo is covered by two compatible BSD-style open source licenses:",
    "",
    "- The IJG (Independent JPEG Group) License, which is listed in",
    "  [README.ijg](README.ijg)",
    "",
    "  This license applies to the libjpeg API library and associated programs,",
    "  including any code inherited from libjpeg and any modifications to that",
    "  code.  Note that the libjpeg-turbo SIMD source code bears the",
    "  [zlib License](https://opensource.org/licenses/Zlib), but in the context of",
    "  the overall libjpeg API library, the terms of the zlib License are subsumed",
    "  by the terms of the IJG License.",
    "",
    "- The Modified (3-clause) BSD License, which is listed below",
    "",
    "  This license applies to the TurboJPEG API library and associated programs, as",
    "  well as the build system.  Note that the TurboJPEG API library wraps the",
    "  libjpeg API library, so in the context of the overall TurboJPEG API library,",
    "  both the terms of the IJG License and the terms of the Modified (3-clause)",
    "  BSD License apply.",
    "",
    "",
    "Complying with the libjpeg-turbo Licenses",
    "=========================================",
    "",
    "This section provides a roll-up of the libjpeg-turbo licensing terms, to the",
    "best of our understanding.  This is not a license in and of itself.  It is",
    "intended solely for clarification.",
    "",
    "1.  If you are distributing a modified version of the libjpeg-turbo source,",
    "    then:",
    "",
    "    1.  You cannot alter or remove any existing copyright or license notices",
    "        from the source.",
    "",
    "        **Origin**",
    "        - Clause 1 of the IJG License",
    "        - Clause 1 of the Modified BSD License",
    "        - Clauses 1 and 3 of the zlib License",
    "",
    "    2.  You must add your own copyright notice to the header of each source",
    "        file you modified, so others can tell that you modified that file.  (If",
    "        there is not an existing copyright header in that file, then you can",
    "        simply add a notice stating that you modified the file.)",
    "",
    "        **Origin**",
    "        - Clause 1 of the IJG License",
    "        - Clause 2 of the zlib License",
    "",
    "    3.  You must include the IJG README file, and you must not alter any of the",
    "        copyright or license text in that file.",
    "",
    "        **Origin**",
    "        - Clause 1 of the IJG License",
    "",
    "2.  If you are distributing only libjpeg-turbo binaries without the source, or",
    "    if you are distributing an application that statically links with",
    "    libjpeg-turbo, then:",
    "",
    "    1.  Your product documentation must include a message stating:",
    "",
    "        This software is based in part on the work of the Independent JPEG",
    "        Group.",
    "",
    "        **Origin**",
    "        - Clause 2 of the IJG license",
    "",
    "    2.  If your binary distribution includes or uses the TurboJPEG API, then",
    "        your product documentation must include the text of the Modified BSD",
    "        License (see below.)",
    "",
    "        **Origin**",
    "        - Clause 2 of the Modified BSD License",
    "",
    "3.  You cannot use the name of the IJG or The libjpeg-turbo Project or the",
    "    contributors thereof in advertising, publicity, etc.",
    "",
    "    **Origin**",
    "    - IJG License",
    "    - Clause 3 of the Modified BSD License",
    "",
    "4.  The IJG and The libjpeg-turbo Project do not warrant libjpeg-turbo to be",
    "    free of defects, nor do we accept any liability for undesirable",
    "    consequences resulting from your use of the software.",
    "",
    "    **Origin**",
    "    - IJG License",
    "    - Modified BSD License",
    "    - zlib License",
    "",
    "",
    "The Modified (3-clause) BSD License",
    "===================================",
    "",
    "Copyright (C)2009-2023 D. R. Commander.  All Rights Reserved.<br>",
    "Copyright (C)2015 Viktor Szathm\xC3""\xA1""ry.  All Rights Reserved.",
    "",
    "Redistribution and use in source and binary forms, with or without",
    "modification, are permitted provided that the following conditions are met:",
    "",
    "- Redistributions of source code must retain the above copyright notice,",
    "  this list of conditions and the following disclaimer.",
    "- Redistributions in binary form must reproduce the above copyright notice,",
    "  this list of conditions and the following disclaimer in the documentation",
    "  and/or other materials provided with the distribution.",
    "- Neither the name of the libjpeg-turbo Project nor the names of its",
    "  contributors may be used to endorse or promote products derived from this",
    "  software without specific prior written permission.",
    "",
    "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\",",
    "AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE",
    "IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE",
    "ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE",
    "LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR",
    "CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF",
    "SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS",
    "INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN",
    "CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)",
    "ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE",
    "POSSIBILITY OF SUCH DAMAGE.",
    "",
    "",
    "Why Two Licenses?",
    "=================",
    "",
    "The zlib License could have been used instead of the Modified (3-clause) BSD",
    "License, and since the IJG License effectively subsumes the distribution",
    "conditions of the zlib License, this would have effectively placed",
    "libjpeg-turbo binary distributions under the IJG License.  However, the IJG",
    "License specifically refers to the Independent JPEG Group and does not extend",
    "attribution and endorsement protections to other entities.  Thus, it was",
    "desirable to choose a license that granted us the same protections for new code",
    "that were granted to the IJG for code derived from their software.",
    "",
    "==== vendor/libjpeg-turbo/README.ijg ====",
    "libjpeg-turbo note:  This file has been modified by The libjpeg-turbo Project",
    "to include only information relevant to libjpeg-turbo, to wordsmith certain",
    "sections, and to remove impolitic language that existed in the libjpeg v8",
    "README.  It is included only for reference.  Please see README.md for",
    "information specific to libjpeg-turbo.",
    "",
    "",
    "The Independent JPEG Group's JPEG software",
    "==========================================",
    "",
    "This distribution contains a release of the Independent JPEG Group's free JPEG",
    "software.  You are welcome to redistribute this software and to use it for any",
    "purpose, subject to the conditions under LEGAL ISSUES, below.",
    "",
    "This software is the work of Tom Lane, Guido Vollbeding, Philip Gladstone,",
    "Bill Allombert, Jim Boucher, Lee Crocker, Bob Friesenhahn, Ben Jackson,",
    "Julian Minguillon, Luis Ortiz, George Phillips, Davide Rossi, Ge' Weijers,",
    "and other members of the Independent JPEG Group.",
    "",
    "IJG is not affiliated with the ISO/IEC JTC1/SC29/WG1 standards committee",
    "(also known as JPEG, together with ITU-T SG16).",
    "",
    "",
    "DOCUMENTATION ROADMAP",
    "=====================",
    "",
    "This file contains the following sections:",
    "",
    "OVERVIEW            General description of JPEG and the IJG software.",
    "LEGAL ISSUES        Copyright, lack of warranty, terms of distribution.",
    "REFERENCES          Where to learn more about JPEG.",
    "ARCHIVE LOCATIONS   Where to find newer versions of this software.",
    "FILE FORMAT WARS    Software *not* to get.",
    "TO DO               Plans for future IJG releases.",
    "",
    "Other documentation files in the distribution are:",
    "",
    "User documentation:",
    "  usage.txt         Usage instructions for cjpeg, djpeg, jpegtran,",
    "                    rdjpgcom, and wrjpgcom.",
    "  *.1               Unix-style man pages for programs (same info as usage.txt).",
    "  wizard.txt        Advanced usage instructions for JPEG wizards only.",
    "  change.log        Version-to-version change highlights.",
    "Programmer and internal documentation:",
    "  libjpeg.txt       How to use the JPEG library in your own programs.",
    "  example.c         Sample code for calling the JPEG library.",
    "  structure.txt     Overview of the JPEG library's internal structure.",
    "  coderules.txt     Coding style rules --- please read if you contribute code.",
    "",
    "Please read at least usage.txt.  Some information can also be found in the JPEG",
    "FAQ (Frequently Asked Questions) article.  See ARCHIVE LOCATIONS below to find",
    "out where to obtain the FAQ article.",
    "",
    "If you want to understand how the JPEG code works, we suggest reading one or",
    "more of the REFERENCES, then looking at the documentation files (in roughly",
    "the order listed) before diving into the code.",
    "",
    "",
    "OVERVIEW",
    "========",
    "",
    "This package contains C software to implement JPEG image encoding, decoding,",
    "and transcoding.  JPEG (pronounced \"jay-peg\") is a standardized compression",
    "method for full-color and grayscale images.  JPEG's strong suit is compressing",
    "photographic images or other types of images that have smooth color and",
    "brightness transitions between neighboring pixels.  Images with sharp lines or",
    "other abrupt features may not compress well with JPEG, and a higher JPEG",
    "quality may have to be used to avoid visible compression artifacts with such",
    "images.",
    "",
    "JPEG is normally lossy, meaning that the output pixels are not necessarily",
    "identical to the input pixels.  However, on photographic content and other",
    "\"smooth\" images, very good compression ratios can be obtained with no visible",
    "compression artifacts, and extremely high compression ratios are possible if",
    "you are willing to sacrifice image quality (by reducing the \"quality\" setting",
    "in the compressor.)",
    "",
    "This software implements JPEG baseline, extended-sequential, progressive, and",
    "lossless compression processes.  Provision is made for supporting all variants",
    "of these processes, although some uncommon parameter settings aren't",
    "implemented yet.  We have made no provision for supporting the hierarchical",
    "processes defined in the standard.",
    "",
    "We provide a set of library routines for reading and writing JPEG image files,",
    "plus two sample applications \"cjpeg\" and \"djpeg\", which use the library to",
    "perform conversion between JPEG and some other popular image file formats.",
    "The library is intended to be reused in other applications.",
    "",
    "In order to support file conversion and viewing software, we have included",
    "considerable functionality beyond the bare JPEG coding/decoding capability;",
    "for example, the color quantization modules are not strictly part of JPEG",
    "decoding, but they are essential for output to colormapped file formats.  These",
    "extra functions can be compiled out of the library if not required for a",
    "particular application.",
    "",
    "We have also included \"jpegtran\", a utility for lossless transcoding between",
    "different JPEG processes, and \"rdjpgcom\" and \"wrjpgcom\", two simple",
    "applications for inserting and extracting textual comments in JFIF files.",
    "",
    "The emphasis in designing this software has been on achieving portability and",
    "flexibility, while also making it fast enough to be useful.  In particular,",
    "the software is not intended to be read as a tutorial on JPEG.  (See the",
    "REFERENCES section for introductory material.)  Rather, it is intended to",
    "be reliable, portable, industrial-strength code.  We do not claim to have",
    "achieved that goal in every aspect of the software, but we strive for it.",
    "",
    "We welcome the use of this software as a component of commercial products.",
    "No royalty is required, but we do ask for an acknowledgement in product",
    "documentation, as described under LEGAL ISSUES.",
    "",
    "",
    "LEGAL ISSUES",
    "============",
    "",
    "In plain English:",
    "",
    "1. We don't promise that this software works.  (But if you find any bugs,",
    "   please let us know!)",
    "2. You can use this software for whatever you want.  You don't have to pay us.",
    "3. You may not pretend that you wrote this software.  If you use it in a",
    "   program, you must acknowledge somewhere in your documentation that",
    "   you've used the IJG code.",
    "",
    "In legalese:",
    "",
    "The authors make NO WARRANTY or representation, either express or implied,",
    "with respect to this software, its quality, accuracy, merchantability, or",
    "fitness for a particular purpose.  This software is provided \"AS IS\", and you,",
    "its user, assume the entire risk as to its quality and accuracy.",
    "",
    "This software is copyright (C) 1991-2020, Thomas G. Lane, Guido Vollbeding.",
    "All Rights Reserved except as specified below.",
    "",
    "Permission is hereby granted to use, copy, modify, and distribute this",
    "software (or portions thereof) for any purpose, without fee, subject to these",
    "conditions:",
    "(1) If any part of the source code for this software is distributed, then this",
    "README file must be included, with this copyright and no-warranty notice",
    "unaltered; and any additions, deletions, or changes to the original files",
    "must be clearly indicated in accompanying documentation.",
    "(2) If only executable code is distributed, then the accompanying",
    "documentation must state that \"this software is based in part on the work of",
    "the Independent JPEG Group\".",
    "(3) Permission for use of this software is granted only if the user accepts",
    "full responsibility for any undesirable consequences; the authors accept",
    "NO LIABILITY for damages of any kind.",
    "",
    "These conditions apply to any software derived from or based on the IJG code,",
    "not just to the unmodified library.  If you use our work, you ought to",
    "acknowledge us.",
    "",
    "Permission is NOT granted for the use of any IJG author's name or company name",
    "in advertising or publicity relating to this software or products derived from",
    "it.  This software may be referred to only as \"the Independent JPEG Group's",
    "software\".",
    "",
    "We specifically permit and encourage the use of this software as the basis of",
    "commercial products, provided that all warranty or liability claims are",
    "assumed by the product vendor.",
    "",
    "",
    "REFERENCES",
    "==========",
    "",
    "We recommend reading one or more of these references before trying to",
    "understand the innards of the JPEG software.",
    "",
    "The best short technical introduction to the JPEG compression algorithm is",
    "        Wallace, Gregory K.  \"The JPEG Still Picture Compression Standard\",",
    "        Communications of the ACM, April 1991 (vol. 34 no. 4), pp. 30-44.",
    "(Adjacent articles in that issue discuss MPEG motion picture compression,",
    "applications of JPEG, and related topics.)  If you don't have the CACM issue",
    "handy, a PDF file containing a revised version of Wallace's article is",
    "available at http://www.ijg.org/files/Wallace.JPEG.pdf.  The file (actually",
    "a preprint for an article that appeared in IEEE Trans. Consumer Electronics)",
    "omits the sample images that appeared in CACM, but it includes corrections",
    "and some added material.  Note: the Wallace article is copyright ACM and IEEE,",
    "and it may not be used for commercial purposes.",
    "",
    "A somewhat less technical, more leisurely introduction to JPEG can be found in",
    "\"The Data Compression Book\" by Mark Nelson and Jean-loup Gailly, published by",
    "M&T Books (New York), 2nd ed. 1996, ISBN 1-55851-434-1.  This book provides",
    "good explanations and example C code for a multitude of compression methods",
    "including JPEG.  It is an excellent source if you are comfortable reading C",
    "code but don't know much about data compression in general.  The book's JPEG",
    "sample code is far from industrial-strength, but when you are ready to look",
    "at a full implementation, you've got one here...",
    "",
    "The best currently available description of JPEG is the textbook \"JPEG Still",
    "Image Data Compression Standard\" by William B. Pennebaker and Joan L.",
    "Mitchell, published by Van Nostrand Reinhold, 1993, ISBN 0-442-01272-1.",
    "Price US$59.95, 638 pp.  The book includes the complete text of the ISO JPEG",
    "standards (DIS 10918-1 and draft DIS 10918-2).",
    "",
    "The original JPEG standard is divided into two parts, Part 1 being the actual",
    "specification, while Part 2 covers compliance testing methods.  Part 1 is",
    "titled \"Digital Compression and Coding of Continuous-tone Still Images,",
    "Part 1: Requirements and guidelines\" and has document numbers ISO/IEC IS",
    "10918-1, ITU-T T.81.  Part 2 is titled \"Digital Compression and Coding of",
    "Continuous-tone Still Images, Part 2: Compliance testing\" and has document",
    "numbers ISO/IEC IS 10918-2, ITU-T T.83.",
    "",
    "The JPEG standard does not specify all details of an interchangeable file",
    "format.  For the omitted details, we follow the \"JFIF\" conventions, revision",
    "1.02.  JFIF version 1 has been adopted as ISO/IEC 10918-5 (05/2013) and",
    "Recommendation ITU-T T.871 (05/2011): Information technology - Digital",
    "compression and coding of continuous-tone still images: JPEG File Interchange",
    "Format (JFIF).  It is available as a free download in PDF file format from",
    "https://www.iso.org/standard/54989.html and http://www.itu.int/rec/T-REC-T.871.",
    "A PDF file of the older JFIF 1.02 specification is available at",
    "http://www.w3.org/Graphics/JPEG/jfif3.pdf.",
    "",
    "The TIFF 6.0 file format specification can be obtained from",
    "http://mirrors.ctan.org/graphics/tiff/TIFF6.ps.gz.  The JPEG incorporation",
    "scheme found in the TIFF 6.0 spec of 3-June-92 has a number of serious",
    "problems.  IJG does not recommend use of the TIFF 6.0 design (TIFF Compression",
    "tag 6).  Instead, we recommend the JPEG design proposed by TIFF Technical Note",
    "#2 (Compression tag 7).  Copies of this Note can be obtained from",
    "http://www.ijg.org/files/.  It is expected that the next revision",
    "of the TIFF spec will replace the 6.0 JPEG design with the Note's design.",
    "Although IJG's own code does not support TIFF/JPEG, the free libtiff library",
    "uses our library to implement TIFF/JPEG per the Note.",
    "",
    "",
    "ARCHIVE LOCATIONS",
    "=================",
    "",
    "The \"official\" archive site for this software is www.ijg.org.",
    "The most recent released version can always be found there in",
    "directory \"files\".",
    "",
    "The JPEG FAQ (Frequently Asked Questions) article is a source of some",
    "general information about JPEG.  It is available at",
    "http://www.faqs.org/faqs/jpeg-faq.",
    "",
    "",
    "FILE FORMAT COMPATIBILITY",
    "=========================",
    "",
    "This software implements ITU T.81 | ISO/IEC 10918 with some extensions from",
    "ITU T.871 | ISO/IEC 10918-5 (JPEG File Interchange Format-- see REFERENCES).",
    "Informally, the term \"JPEG image\" or \"JPEG file\" most often refers to JFIF or",
    "a subset thereof, but there are other formats containing the name \"JPEG\" that",
    "are incompatible with the original JPEG standard or with JFIF (for instance,",
    "JPEG 2000 and JPEG XR).  This software therefore does not support these",
    "formats.  Indeed, one of the original reasons for developing this free software",
    "was to help force convergence on a common, interoperable format standard for",
    "JPEG files.",
    "",
    "JFIF is a minimal or \"low end\" representation.  TIFF/JPEG (TIFF revision 6.0 as",
    "modified by TIFF Technical Note #2) can be used for \"high end\" applications",
    "that need to record a lot of additional data about an image.",
    "",
    "",
    "TO DO",
    "=====",
    "",
    "Please send bug reports, offers of help, etc. to jpeg-info@jpegclub.org.",
    "",
};

size_t rubraview_notice_lines(const char *const **out) {
    if (out) *out = LINES;
    return sizeof(LINES) / sizeof(LINES[0]);
}
